/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _TechAppGradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
    	// 	grr; aka most useful file atm
    }
}
